name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: yarn install

      - name: set development version
        run: node .github/version-bump.js "$(git rev-parse --short HEAD)"

      - name: build
        run: yarn build

      - name: upload dist
        uses: actions/upload-artifact@v3.1.0
        with:
          name: dist
          path: |
            manifest.json
            main.js

  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: yarn install

      - name: test
        run: yarn test

  lint:
    runs-on: ubuntu-latest
    name: lint:prod
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: yarn install

      - name: lint
        run: yarn lint
