name: CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_LINK: https://github.com/leonhma/obsidian-functionplot/actions/runs/${{ github.run_id }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: set development version
        run: node .github/version-bump.js "$(git rev-parse --short HEAD)"

      - name: build
        run: pnpm run build:prod

      - name: upload dist
        uses: actions/upload-artifact@v3.1.0
        with:
          name: obsidian-functionplot
          path: |
            manifest.json
            main.js

  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: test
        run: pnpm run test

  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: lint
        run: pnpm run lint
