name: release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 18

      - name: Checkout
        uses: actions/checkout@v2.4.2

      - name: Install
        run: |
          sudo apt-get -y install moreutils
          pnpm install

      - name: Lint
        run: pnpm run lint:prod

      - name: Test
        run: pnpm run test

      - name: Run version-bump
        run: node .github/version-bump.js ${{ github.event.release.tag_name }}

      # build release notes
      - name: Update release notes
        run: node .github/release-notes.js ${{ github.event.release.tag_name }} ${{ github.event.release.body }}

      # build now, so that no side-effects when build fails and release get deleted
      - name: Build
        run: |
          pnpm run build:release
          mkdir obsidian-functionplot
          cp main.js manifest.json styles.css obsidian-functionplot
          zip -r obsidian-functionplot.zip obsidian-functionplot
          ls

      - name: Commit and push changes
        run: |
          git config --global user.name "leonhma"
          git config --global user.email "leonhardmasche@gmail.com"

          git add -A
          git commit -m "chore(versions): index minAppVersion for latest release"
          git push origin master

      - name: Upload assets to a Release
        uses: AButler/upload-release-assets@v2.0
        with:
          repo-token: ${{ github.token }}
          files: "main.js;manifest.json;obsidian-functionplot.zip"

      - uses: actions/github-script@v4
        if: failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo } = context.repo
            await github.repos.deleteRelease({ owner, repo, release_id: context.payload.release.id })
